# docker run -it -e PORT=8080 -e PROJECT_ID=$PROJECT_ID -e INSTANCE_NAME=test-instance -e DATABASE_NAME=game -e CONNECTION_STRING="host=localhost port=5432 database=game" -p 8080:8080 test

version: '3'
services:
  api:
    build: .
    ports:
    - "8080:8080"

    environment:
    - PORT=8080
    - PROJECT_ID=${GOOGLE_CLOUD_PROJECT}
    - INSTANCE_NAME=test-instance
    - CONNECTION_STRING="host=localhost"
    - DATABASE_NAME=music

    volumes:
    # If you're in Cloud Shell, change it as below,
    # - ${CLOUDSDK_CONFIG}:/.config/gcloud
    - ${HOME}/.config:/root/.config
